import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { authOptions } from "@/lib/auth";
import { getServerSession } from "next-auth";
import SessionWrapper from "@/components/sessionprovider/page";

const myFont = localFont({
  src: "../../public/fonts/Arial.ttf",
  variable: "--font-my-font",
});

export const metadata: Metadata = {
  title: "Тест бүртгэлийн систем",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={`${myFont.variable} antialiased`}>
        <SessionWrapper session={session}>{children}</SessionWrapper>
      </body>
    </html>
  );
}
